environment:
  BINSTAR_TOKEN: o5nTvV9PwJQgt5HXoqAl1iWi1ivyOrGb9ZL20puP4xklAEfvN/0EDHbhDHpVwjC7
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\ci\\appveyor\\run_with_env.cmd"
    CONDA_NPY: "112"
    PYTHONHASHSEED: "0"

  matrix:

    - MINICONDA_PYTHON: "C:\\Miniconda3"
      CONDA_PY: "35"

    - MINICONDA_PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "35"
      ARCH: "64"

    - MINICONDA_PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      ARCH: "64"

    - MINICONDA_PYTHON: "C:\\Miniconda3-x64"
      CONDA_PY: "36"
      ARCH: "64"
      CONDA_NPY: "113"

install:
  - "SET PATH=%MINICONDA_PYTHON%;%MINICONDA_PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true 
  - conda config --add channels conda-forge
  - conda install -q conda-build=2.1.15 jinja2

  # use agg backend in matplotlib to avoid gui popup, which can not be closed.
  - echo %userprofile%
  - mkdir %userprofile%\\.matplotlib
  - "echo backend: agg > %userprofile%\\.matplotlib\\matplotlibrc"

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  - "%CMD_IN_ENV% conda build -q devtools/conda-recipe"

#on_success:
#  - devtools/ci/appveyor/after_success.bat

