environment:
  global:
    # SDK v7.0 MSVC Express 2008's SetEnv.cmd script will fail if the
    # /E:ON and /V:ON options are not enabled in the batch script intepreter
    # See: http://stackoverflow.com/a/13751649/163740
    CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\devtools\\ci\\appveyor\\run_with_env.cmd"
    PYTHONHASHSEED: "0"

  matrix:
    - MINICONDA_PYTHON: "C:\\Miniconda35"
      CONDA_PY: "35"

    - MINICONDA_PYTHON: "C:\\Miniconda35-x64"
      CONDA_PY: "35"
      ARCH: "64"

    - MINICONDA_PYTHON: "C:\\Miniconda36-x64"
      CONDA_PY: "36"
      ARCH: "64"

install:
  - "SET PATH=%MINICONDA_PYTHON%;%MINICONDA_PYTHON%\\Scripts;%PATH%;"

  - conda config --set always_yes true
  - conda config --add channels conda-forge
  - conda install -q conda-build=3

build: false # Not a C# project, build stuff at the test step instead.

test_script:
  # run testsuite and upload test results to AppVeyor; return exit code of testsuite
  - "%CMD_IN_ENV% conda build -q devtools/conda-recipe"

#on_finish:
  # upload test results to AppVeyor
 # - ps: $wc = New-Object 'System.Net.WebClient';
 #       $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)",
 #       C:\Users\appveyor\reports\xunit.xml))

